#!/usr/bin/env bash
#
# Redirect setup — walks you through creating Cloudflare Redirect Rules to
# send www.shameel.dev and shameel.barchy.online to shameel.dev (301).
#
# Generated by the /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  DIM=$(tput dim)
  BOLD=$(tput bold)
  RESET=$(tput sgr0)
else
  BLUE="" GREEN="" YELLOW="" DIM="" BOLD="" RESET=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() { printf '\033c'; }

banner() {
  _clear
  printf '\n  %s%s%s\n' "$BOLD" "$1" "$RESET"
  printf '  %s\n' "─"
  printf '\n'
}

stage() {
  _clear
  _STAGE_INDEX=$(( _STAGE_INDEX + 1 ))
  printf '\n  %s [%d/%d] %s%s\n\n' "$GREEN" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" 2>/dev/null &
  elif command -v open >/dev/null 2>&1; then
    open "$url" 2>/dev/null &
  elif command -v wslview >/dev/null 2>&1; then
    wslview "$url" 2>/dev/null &
  fi
  printf '  %s→%s Opened %s%s%s\n' "$BLUE" "$RESET" "$DIM" "$url" "$RESET"
}

pause() { printf '\n  %s%s%s' "$DIM" "$1" "$RESET"; read -r; }

confirm() {
  printf '\n  %s%s%s' "$DIM" "$1 [y/N] " "$RESET"
  read -r answer
  [[ "$answer" =~ ^[Yy] ]]
}

_existing() { grep -oP "^${1}=\K.*" "$ENV_FILE" 2>/dev/null || true; }

ask() {
  local key="$1" prompt="$2"
  local existing
  existing=$(_existing "$key")
  if [[ -n "$existing" ]]; then
    printf '  %s%s%s (Enter to keep current): ' "$DIM" "$prompt" "$RESET"
  else
    printf '  %s%s%s: ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r value
  value="${value:-$existing}"
  eval "$key=\"\$value\""
}

ask_secret() {
  local key="$1" prompt="$2"
  printf '  %s%s%s: ' "$BOLD" "$prompt" "$RESET"
  read -rs value
  printf '\n'
  eval "$key=\"\$value\""
}

write_env() {
  local key="$1" value="$2"
  if [[ -f "$ENV_FILE" ]] && grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    echo "${key}=${value}" >> "$ENV_FILE"
  fi
  WRITTEN_ENV+=("$key")
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    echo "$value" | gh secret set "$name" 2>/dev/null && WRITTEN_SECRET+=("$name")
  else
    warn "gh CLI unavailable or not authed — skipped setting secret $name"
    SKIPPED+=("$name")
  fi
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh variable set "$name" --body "$value" 2>/dev/null
  else
    warn "gh CLI unavailable or not authed — skipped setting variable $name"
    SKIPPED+=("$name")
  fi
}

finish() {
  _clear
  printf '\n  %sDone!%s\n\n' "$GREEN" "$RESET"
  if [[ ${#WRITTEN_ENV[@]} -gt 0 ]]; then
    printf '  %sEnv updated:%s %s\n' "$BOLD" "$RESET" "${WRITTEN_ENV[*]}"
  fi
  if [[ ${#WRITTEN_SECRET[@]} -gt 0 ]]; then
    printf '  %sSecrets set:%s %s\n' "$BOLD" "$RESET" "${WRITTEN_SECRET[*]}"
  fi
  if [[ ${#SKIPPED[@]} -gt 0 ]]; then
    printf '  %sSkipped:%s %s\n' "$YELLOW" "$RESET" "${SKIPPED[*]}"
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=2

banner "Cloudflare Redirect Rules → shameel.dev"

# ── Stage 1 — www.shameel.dev → shameel.dev ──────────────────────────────
stage "Redirect: www.shameel.dev → shameel.dev"
say "Create a 301 redirect so www.shameel.dev forwards to shameel.dev."
open_url "https://dash.cloudflare.com/?to=/:account/:zone/rules/redirect-rules"
step "Select the shameel.dev zone from the zone picker (top bar)."
step "Rules → Rules → Create rule → Single redirect."
step "Rule name: www-to-apex"
step 'When: Field "Hostname", Operator "equals", Value "www.shameel.dev"'
step 'Then: Type "Dynamic", Expression: concat("https://shameel.dev", http.request.uri.path)'
step "Status code: 301 (Permanent redirect)"
step "Click Save, then Deploy."
note "This sends all www.shameel.dev traffic to shameel.dev at the edge."
pause "Done — redirect rule deployed?"

# ── Stage 2 — shameel.barchy.online → shameel.dev ────────────────────────
stage "Redirect: shameel.barchy.online → shameel.dev"
say "Create a 301 redirect so shameel.barchy.online forwards to shameel.dev."
open_url "https://dash.cloudflare.com/?to=/:account/:zone/rules/redirect-rules"
step "Switch to the barchy.online zone from the zone picker (top bar)."
step "Rules → Rules → Create rule → Single redirect."
step "Rule name: barchy-to-shameel"
step 'When: Field "Hostname", Operator "equals", Value "shameel.barchy.online"'
step 'Then: Type "Dynamic", Expression: concat("https://shameel.dev", http.request.uri.path)'
step "Status code: 301 (Permanent redirect)"
step "Click Save, then Deploy."
note "This sends all shameel.barchy.online traffic to shameel.dev at the edge."
note "After this, the old domain fully points to the new one."
pause "Done — redirect rule deployed?"

# ──────────────────────────────────────────────────────────────────────────

finish
