#!/usr/bin/env bash
#
# Resend setup — walks you through connecting the portfolio contact form to
# Resend: API key, domain verification on shameel.barchy.online, then writes
# RESEND_API_KEY / RESEND_FROM / RESEND_TO to .env (and optionally sets the
# API key as a Cloudflare Worker secret for production).
#
# Generated by the /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n'
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say() { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

set_wrangler_secret() {
  local name="$1" value="$2"
  if command -v wrangler >/dev/null 2>&1; then
    if printf '%s' "$value" | wrangler secret put "$name" --name protfolio >/dev/null 2>&1; then
      WRITTEN_SECRET+=("Cloudflare $name")
      printf '  %s✓ set%s Cloudflare Worker secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
    SKIPPED+=("Cloudflare secret $name (wrangler not logged in or failed)")
    warn "wrangler secret put $name failed — set it in CF dashboard → Worker → Settings → Variables"
    return
  fi
  SKIPPED+=("Cloudflare secret $name (wrangler not installed)")
  warn "wrangler not found — set $name in the Cloudflare dashboard instead"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section.
# ──────────────────────────────────────────────────────────────────────────

SENDING_DOMAIN="shameel.barchy.online"
DEFAULT_FROM="Portfolio <noreply@${SENDING_DOMAIN}>"
RECIPIENT="muhammadshameelks@gmail.com"

TOTAL_STAGES=6

banner "Resend setup"

# ── Stage 1 — Resend account ──────────────────────────────────────────────
stage "Resend account"
say "Create (or log into) a Resend account. This is the service your contact"
say "form uses to email you — no database, SendGrid-style API."
open_url "https://resend.com"
step "If you don't have an account, click 'Get started' / sign up (GitHub or email)."
step "Confirm your email if prompted and land on the Resend dashboard."
note "Tip: the Hacker plan's free 100 emails/day is plenty for a portfolio contact form."
pause "Done — signed in to Resend?"

# ── Stage 2 — API key ────────────────────────────────────────────────────
stage "Resend — API key"
say "Create an API key. The contact form sends through this."
open_url "https://resend.com/api-keys"
step "Click 'Create API Key'."
step "Give it a name (e.g. 'protfolio-contact'), permission 'Sending access', click Create."
step "Copy the key (starts with re_) — Resend only shows it once."
ask_secret RESEND_API_KEY "Paste the API key (re_...):"
write_env RESEND_API_KEY "$RESEND_API_KEY"

# ── Stage 3 — Add sending domain ─────────────────────────────────────────
stage "Resend — add domain"
say "Verify ${SENDING_DOMAIN}. This lets Resend send as noreply@${SENDING_DOMAIN}"
say "instead of the generic onboarding@resend.dev (better deliverability)."
open_url "https://resend.com/domains"
step "Click 'Add Domain'."
step "Enter ${SENDING_DOMAIN} and select 'Us' (production)."
step "Choose region (us-east recommended) and click 'Add'."
note "You'll then see DNS records to add — leave this tab open for the next stage."
pause "Domain added — DNS records are showing?"

# ── Stage 4 — Add DNS records in Cloudflare ──────────────────────────────
stage "Cloudflare — add DNS records"
say "Add the 3 TXT records Resend gave you to Cloudflare DNS for ${SENDING_DOMAIN}."
say "Leave the Resend 'domains' tab open; this wizard opens Cloudflare next."
open_url "https://dash.cloudflare.com"
step "Select the barchy.online zone → DNS → Records."
step "For EACH of the 3 records Resend shows: click 'Add record'."
step "  - Type: TXT  ·  Name: as Resend specifies (often the domain or _dmarc)  ·  Content: paste the value  ·  TTL: Auto or 1h"
note "Resend typically shows 1 SPF (Verify and receive) + 2 DKIM (sending) records."
note "If you already verified this domain before, you can skip this stage — Enter to continue."
pause "Added all DNS records in Cloudflare?"

# ── Stage 5 — Verify domain in Resend ────────────────────────────────────
stage "Resend — verify domain"
say "Tell Resend to re-check the DNS records you just added."
open_url "https://resend.com/domains"
step "Go to Domains → open ${SENDING_DOMAIN}."
step "Wait a minute or two for DNS to propagate, then click 'Verify'."
note "DNS can take a few minutes. If it fails, wait 60s and Verify again."
pause "Is ${SENDING_DOMAIN} now status 'Verified'?"

# ── Stage 6 — Sender + recipient ─────────────────────────────────────────
stage "Sender & recipient"
say "Set the from-address (match the domain you just verified) and your inbox."
ask RESEND_FROM "Email sender (Format: 'Name <email@domain>')" && RESEND_FROM="${RESEND_FROM:-$DEFAULT_FROM}"
ask RESEND_TO "Where should inquiries land? (your Gmail)" && RESEND_TO="${RESEND_TO:-$RECIPIENT}"
write_env RESEND_FROM "$RESEND_FROM"
write_env RESEND_TO "$RESEND_TO"

# ── Optional — production secret on Cloudflare ───────────────────────────
if confirm "Push RESEND_API_KEY to the Cloudflare Worker for production?"; then
  say "Setting RESEND_API_KEY as a Cloudflare Worker secret (protfolio)."
  set_wrangler_secret RESEND_API_KEY "$RESEND_API_KEY"
fi

finish
